CREATE TABLE `account` (
   `ACCOUNT_ID` int(11) NOT NULL AUTO_INCREMENT,
   `USER_LOGIN` varchar(100) NOT NULL DEFAULT '',
   `EMAIL` varchar(100) NOT NULL DEFAULT '',
   `PASSWORD` varchar(100) NOT NULL DEFAULT '',
   `FIRST_NAME` varchar(100) DEFAULT NULL,
   `LAST_NAME` varchar(100) DEFAULT NULL,
   `CITY` varchar(100) DEFAULT NULL,
   `STATE` varchar(100) DEFAULT NULL,
   `ZIP` varchar(100) DEFAULT NULL,
   `PHONE_NUMBER` varchar(45) DEFAULT NULL,
   `COUNTRY` varchar(100) DEFAULT NULL,
   `ADDRESS` varchar(1000) DEFAULT NULL,
   `ADDRESS2` varchar(1000) DEFAULT NULL,
   `ENABLED` tinyint(1) DEFAULT 1,
   `SHIP_NAME` varchar(200) DEFAULT NULL,
   `SHIP_CITY` varchar(100) DEFAULT NULL,
   `SHIP_STATE` varchar(100) DEFAULT NULL,
   `SHIP_ZIP` varchar(100) DEFAULT NULL,
   `SHIP_PHONE` varchar(45) DEFAULT NULL,
   `SHIP_COUNTRY` varchar(100) DEFAULT NULL,
   `SHIP_ADDRESS` varchar(1000) DEFAULT NULL,
   `SHIP_ADDRESS2` varchar(1000) DEFAULT NULL,    
   PRIMARY KEY (`ACCOUNT_ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;
 
CREATE TABLE `cart` (
   `CART_ID` int(11) NOT NULL AUTO_INCREMENT,
   `ACCOUNT_ID` int(11) DEFAULT NULL,
   `SESSION_ID` varchar(100) DEFAULT NULL,
   `INVENTORY_DETAIL_ID` int(11) NOT NULL DEFAULT 0,
   `QUANTITY` int(11) NOT NULL DEFAULT 1,
   `PRICE_PER_ITEM` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
   `SHIPPING_COST` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
   `TAX` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
   PRIMARY KEY (`CART_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE `inventory` (
   `INVENTORY_ID` int(11) NOT NULL,
   `INVENTORY_TYPE_CD` INT NOT NULL,
   `INVENTORY_CAT_CD` INT NOT NULL, 
   `INVENTORY_TXT` varchar(45) DEFAULT NULL,
   `INVENTORY_DESCRIPTION` VARCHAR(5000) NOT NULL,
   `INVENTORY_CARE` VARCHAR(5000) NULL,
   `INVENTORY_SIZE_DESC` VARCHAR(5000) NULL,
   `BRAND` VARCHAR(45) NOT NULL,   
   `PRICE_USD` DECIMAL(6,2) DEFAULT NULL,
   `IN_STOCK` tinyint(1) DEFAULT NULL,
   `IMG` VARCHAR(100) NULL,
   PRIMARY KEY (`INVENTORY_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
 CREATE TABLE `inventory_detail` (
  `INVENTORY_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
  `INVENTORY_ID` INT NOT NULL,
  `PRODUCT_CODE` VARCHAR(45) NOT NULL,
  `STOCK_QUANTITY` INT NOT NULL,
  `SIZE` VARCHAR(45) NOT NULL,
  `COLOR` VARCHAR(45) NOT NULL,
  `THUMBNAIL1` VARCHAR(100) NULL,
  `THUMBNAIL2` VARCHAR(100) NULL,
  `THUMBNAIL3` VARCHAR(100) NULL,
  `THUMBNAIL4` VARCHAR(100) NULL,
  `THUMBNAIL5` VARCHAR(100) NULL,
  PRIMARY KEY (`INVENTORY_DETAIL_ID`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
CREATE TABLE `inventory_category_code` (
   `inventory_cat_cd` int(11) NOT NULL,
   `inventory_cat_txt` varchar(45) DEFAULT NULL,
   `inventory_cat_description` varchar(5000) DEFAULT NULL,
   PRIMARY KEY (`inventory_cat_cd`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;  
 
CREATE TABLE `inventory_type_code` (
   `inventory_type_cd` int(11) NOT NULL,
   `inventory_type_txt` varchar(45) DEFAULT NULL,
   `inventory_type_description` varchar(5000) DEFAULT NULL,
   PRIMARY KEY (`inventory_type_cd`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `roles` (
   `USER_LOGIN` varchar(100) NOT NULL DEFAULT '',
   `ROLE` varchar(100) NOT NULL DEFAULT '',
   PRIMARY KEY (`USER_LOGIN`,`ROLE`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE `session_account` (
   `SESSION_ID` varchar(100) NOT NULL,
   `EMAIL` varchar(100) DEFAULT NULL,
   `FIRST_NAME` varchar(100) DEFAULT NULL,
   `LAST_NAME` varchar(100) DEFAULT NULL,
   `CITY` varchar(100) DEFAULT NULL,
   `STATE` varchar(100) DEFAULT NULL,
   `ZIP` varchar(100) DEFAULT NULL,
   `PHONE_NUMBER` varchar(45) DEFAULT NULL,
   `COUNTRY` varchar(100) DEFAULT NULL,
   `ADDRESS` varchar(1000) DEFAULT NULL,
   `ADDRESS2` varchar(1000) DEFAULT NULL,
   `SHIP_NAME` varchar(200) DEFAULT NULL,
   `SHIP_CITY` varchar(100) DEFAULT NULL,
   `SHIP_STATE` varchar(100) DEFAULT NULL,
   `SHIP_ZIP` varchar(100) DEFAULT NULL,
   `SHIP_PHONE` varchar(45) DEFAULT NULL,
   `SHIP_COUNTRY` varchar(100) DEFAULT NULL,
   `SHIP_ADDRESS` varchar(1000) DEFAULT NULL,
   `SHIP_ADDRESS2` varchar(1000) DEFAULT NULL,    
   PRIMARY KEY (`SESSION_ID`)
 ) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8; 

CREATE TABLE `sizing` (
   `SIZING_ID` int(11) NOT NULL,
   `INVENTORY_ID` int(11) DEFAULT NULL,
   `BUST` int(11) DEFAULT NULL,
   `WAIST` int(11) DEFAULT NULL,
   `HIP` int(11) DEFAULT NULL,
   `SHOULDER_WIDTH` int(11) DEFAULT NULL,
   `FRONT_BODY_LENGTH` int(11) DEFAULT NULL,
   PRIMARY KEY (`SIZING_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `transaction` (
   `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
   `ACCOUNT_ID` int(11) DEFAULT NULL,
   `SESSION_ID` varchar(100) DEFAULT NULL,
   `CART_ID` int(11) DEFAULT NULL,   
   `ORDER_QUANTITY` int(11) DEFAULT NULL,
   `SHIP_NAME` varchar(200) DEFAULT NULL,
   `SHIP_ADDRESS` varchar(1000) DEFAULT NULL,
   `SHIP_ADDRESS2` varchar(1000) DEFAULT NULL,
   `CITY` varchar(100) DEFAULT NULL,
   `STATE` varchar(100) DEFAULT NULL,
   `ZIP` varchar(100) DEFAULT NULL,
   `COUNTRY` varchar(100) DEFAULT NULL,
   `PHONE` varchar(45) DEFAULT NULL,
   `SHIPPING_COST` DECIMAL(6,2) DEFAULT NULL,
   `TAX` varchar(45) DEFAULT NULL,
   `ORDER_EMAIL` varchar(100) DEFAULT NULL,
   `DATE` timestamp NULL DEFAULT NULL,
   `SHIPPED` tinyint(1) DEFAULT NULL,
   `TRACKING_NUMBER` BIGINT(11) DEFAULT NULL,
   `INVENTORY_DETAIL_ID` int(11) DEFAULT NULL,
   `ORDER_COST` DECIMAL(6,2) DEFAULT NULL,
   `MESSAGE` varchar(5000) DEFAULT NULL,
   `CARD_TYPE` varchar(15) NOT NULL,
   `CARD_NUMBER` int(16) NOT NULL,
   `CARD_SECURITY_CODE` int(10) NOT NULL,
   `CONFIRMED` tinyint(1) DEFAULT 0,  
   PRIMARY KEY (`TRANSACTION_ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

 