INSERT INTO ACCOUNT (ACCOUNT_ID,USER_LOGIN,ENABLED) VALUES (-1,'anonymousUser',1);
INSERT INTO ACCOUNT (ACCOUNT_ID,USER_LOGIN,PASSWORD,FIRST_NAME,ENABLED) VALUES (-2,'pankaj','pankaj123','pankajmayne',1);
INSERT INTO ACCOUNT (ACCOUNT_ID,USER_LOGIN,EMAIL,PASSWORD,FIRST_NAME,LAST_NAME,CITY,STATE,ZIP,PHONE_NUMBER,COUNTRY,ADDRESS,ADDRESS2,ENABLED) VALUES (11,'zuk','dirk@zuk.com','pass','dudemayne','zuk','citytyy','vastate','12345','12043834980','United State','adddresssszzszsz','addresszsz2',1);
COMMIT;