INSERT INTO INVENTORY_DETAIL (INVENTORY_DETAIL_ID,INVENTORY_ID,PRODUCT_CODE,STOCK_QUANTITY,SIZE,COLOR,THUMBNAIL1) VALUES (-1,-111,'ABP30203CX','129','XS','Black','/resources/img/product1.jpg');
INSERT INTO INVENTORY_DETAIL (INVENTORY_DETAIL_ID,INVENTORY_ID,PRODUCT_CODE,STOCK_QUANTITY,SIZE,COLOR,THUMBNAIL1) VALUES (-2,-112,'AND832L9','40','M','Blue','/resources/img/product2.jpg');
INSERT INTO INVENTORY_DETAIL (INVENTORY_DETAIL_ID,INVENTORY_ID,PRODUCT_CODE,STOCK_QUANTITY,SIZE,COLOR,THUMBNAIL1) VALUES (-3,-113,'AND832Q5','23','XS','Red','/resources/img/product2.jpg');
COMMIT;