INSERT INTO ROLES (USER_LOGIN,ROLE) VALUES ('anonymousUser','Admin');
INSERT INTO ROLES (USER_LOGIN,ROLE) VALUES ('pankaj','Admin');
INSERT INTO ROLES (USER_LOGIN,ROLE) VALUES ('zuk','Admin');
COMMIT;