INSERT INTO INVENTORY_CATEGORY_CODE (INVENTORY_CAT_CD,INVENTORY_CAT_TXT,INVENTORY_CAT_DESCRIPTION) VALUES (100,'Jackets','Inventory of the jackets that we sell at the FauxShop');
INSERT INTO INVENTORY_CATEGORY_CODE (INVENTORY_CAT_CD,INVENTORY_CAT_TXT,INVENTORY_CAT_DESCRIPTION) VALUES (101,'Shirts','Inventory of the shirts that we sell at the FauxShop');
INSERT INTO INVENTORY_CATEGORY_CODE (INVENTORY_CAT_CD,INVENTORY_CAT_TXT,INVENTORY_CAT_DESCRIPTION) VALUES (102,'Pants','Inventory of the pants that we sell at the FauxShop');
COMMIT;