INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (10,'Leather Jacket','Leather Jacket Description');
INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (11,'Pleather Shirt','Pleather Shirt Description');
COMMIT;