INSERT INTO EMPLOYEES (USERNAME,PASSWORD,ENABLED) VALUES ('anonymousUser','',1);
INSERT INTO EMPLOYEES (USERNAME,PASSWORD,ENABLED) VALUES ('pankaj','pankaj123',1);
INSERT INTO EMPLOYEES (USERNAME,PASSWORD,ENABLED) VALUES ('zuk','pass',1);
COMMIT;