INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (10,'Pleather Jacket','Pleather Jacket Description');
INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (11,'Pleather Shirt','Pleather Shirt Description');
INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (12,'Pleather Pants','Pleather Pants Description');
INSERT INTO INVENTORY_TYPE_CODE (INVENTORY_TYPE_CD,INVENTORY_TYPE_TXT,INVENTORY_TYPE_DESCRIPTION) VALUES (13,'Hemp Shirt','Hemp Shirt Description');
COMMIT;